# Generated by Django 5.2.10 on 2026-01-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('purchase_price', models.FloatField()),
                ('monthly_rent', models.FloatField()),
                ('maintenance_cost', models.FloatField()),
            ],
        ),
    ]
