# Generated by Django 5.2.11 on 2026-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('RENT_CHANGE', 'Change Rent'), ('MAINTENANCE_CHANGE', 'Change Maintenance'), ('PROPERTY_REVALUATION', 'Change Property Value')], max_length=20),
        ),
    ]
