# Generated by Django 5.2.11 on 2026-02-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_image_alter_proposal_proposal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rentpayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
